### ISSUE TITLE
can-zone can not handle addEventListener

### ISSUE THREAD

**Issue by pYr0x** [canjs/can-zone#104]
there is a problem with `done-autorender`.
the problem seems to be in `steal-css` where we using `addEventListener` to know when the css is injected.
https://github.com/stealjs/steal-css/blob/master/css.js#L110-L112

**Comment by matthewp** [comment]
What should can-zone do with addEventListener?  Wait for the event to occur?

**Comment by justinbmeyer** [comment]
Not generically. Perhaps some plugins can set this up, but hard to know which specific events should be waited on, and which shouldn't.

**Comment by pYr0x** [comment]
i dont know what we can do.
if you remove the `addEventListener` on the `steal-css` plugin and use the polling `onloadCss` can-zone will not fail.

maybe register event listener through a proxy on can-zone

**Comment by matthewp** [comment]
I don't understand what you mean when you say can-zone will fail? Do you mean it will throw an error?

**Comment by pYr0x** [comment]
no, it will not resolve.
while debugging, javascript will never reached this line
https://github.com/donejs/autorender/blob/master/src/template.txt#L136
or that line
https://github.com/donejs/autorender/blob/master/src/template.txt#L102

**Comment by matthewp** [comment]
Looked more into this. What's happening is that a setTimeout is created and then later gets cleared. Because clearTimeout is inside of the event handler, it is not deducted from the Zone's counter.

The fix is to make sure that event handlers are run within the Zone. It won't increment the counter, but it will just make sure that it is Zone wrapped.  We do this already for MutationObserver.  https://github.com/canjs/can-zone/blob/master/lib/tasks.js#L182

**Comment by pYr0x** [comment]
but that mean, that steal-css depends on can-zone?

how can we wrap `addEventListener` ?

**Comment by matthewp** [comment]
steal-css doesn't depend on can-zone, done-autorender does.  I'm working on a fix for this.

**Comment by matthewp** [comment]
This is fixed in can-zone 0.6.3, tested your app and its working now @pYr0x
